"""add item fields to supplier_quotes

Revision ID: 4eecc7d8d320
Revises: rename_rfqitem_cols
Create Date: 2025-10-31 18:32:03.991983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4eecc7d8d320'
down_revision = 'rename_rfqitem_cols'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('item_description', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('quantity_requested', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unit', mysql.VARCHAR(length=50), nullable=True))
        batch_op.create_index('ix_supplier_quotes_supplier_rfq_item', ['supplier_id', 'rfq_id', 'item_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_quotes', schema=None) as batch_op:
        batch_op.drop_index('ix_supplier_quotes_supplier_rfq_item')
        batch_op.drop_column('unit')
        batch_op.drop_column('quantity_requested')
        batch_op.drop_column('item_description')
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###
