"""add_category_to_supplier_quotes_for_grouping

Revision ID: 85f668c04a07
Revises: 914378132728
Create Date: 2025-11-04 13:35:49.944034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85f668c04a07'
down_revision = '914378132728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('invoice_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='发票代码（10-12位）',
               existing_nullable=True)
        batch_op.alter_column('buyer_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='购买方名称',
               existing_nullable=True)
        batch_op.alter_column('buyer_tax_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='购买方纳税人识别号/统一社会信用代码',
               existing_nullable=True)
        batch_op.alter_column('seller_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='销售方名称（供应商）',
               existing_nullable=True)
        batch_op.alter_column('seller_tax_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='销售方纳税人识别号',
               existing_nullable=True)
        batch_op.alter_column('amount_before_tax',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               comment=None,
               existing_comment='金额合计（不含税）',
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               comment=None,
               existing_comment='价税合计',
               existing_nullable=True)
        batch_op.alter_column('remark',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='备注说明（中国发票格式）',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_invoices_buyer_tax_id'))
        batch_op.drop_index(batch_op.f('idx_invoices_invoice_code'))
        batch_op.drop_index(batch_op.f('idx_invoices_seller_tax_id'))

    with op.batch_alter_table('rfqs', schema=None) as batch_op:
        batch_op.alter_column('payment_terms',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='付款周期(天)',
               existing_server_default=sa.text("'90'"))

    with op.batch_alter_table('supplier_quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', mysql.VARCHAR(length=100), nullable=True, comment='品类名称，如"刀具/铣削刀具"'))
        batch_op.alter_column('payment_terms',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='供应商报价付款周期(天)',
               existing_server_default=sa.text("'90'"))
        batch_op.drop_index(batch_op.f('idx_sq_quote_number'))
        batch_op.create_index(batch_op.f('ix_supplier_quotes_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_quotes_quote_number'), ['quote_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_supplier_quotes_status'), ['status'], unique=False)
        batch_op.create_index('ix_supplier_quotes_supplier_rfq_category', ['supplier_id', 'rfq_id', 'category'], unique=True)

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.alter_column('credit_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='信用代码',
               existing_nullable=True)
        batch_op.alter_column('tax_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='税号',
               existing_nullable=True)
        batch_op.alter_column('legal_representative',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='法定代表人',
               existing_nullable=True)
        batch_op.alter_column('registered_capital',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='注册资本（万元）',
               existing_nullable=True)
        batch_op.alter_column('registered_address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300),
               comment=None,
               existing_comment='注册地址',
               existing_nullable=True)
        batch_op.alter_column('established_date',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='成立日期',
               existing_nullable=True)
        batch_op.alter_column('company_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='企业类型',
               existing_nullable=True)
        batch_op.alter_column('business_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='经营状态',
               existing_nullable=True)
        batch_op.alter_column('company_phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment=None,
               existing_comment='公司电话',
               existing_nullable=True)
        batch_op.alter_column('fax',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment=None,
               existing_comment='传真',
               existing_nullable=True)
        batch_op.alter_column('website',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='公司网站',
               existing_nullable=True)
        batch_op.alter_column('office_address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300),
               comment=None,
               existing_comment='办公地址',
               existing_nullable=True)
        batch_op.alter_column('postal_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='邮政编码',
               existing_nullable=True)
        batch_op.alter_column('company_description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='公司简介',
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='描述',
               existing_nullable=True)
        batch_op.alter_column('main_products',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='主营产品',
               existing_nullable=True)
        batch_op.alter_column('annual_revenue',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='年营业额（万元）',
               existing_nullable=True)
        batch_op.alter_column('employee_count',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='员工人数',
               existing_nullable=True)
        batch_op.alter_column('factory_area',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='工厂面积（平方米）',
               existing_nullable=True)
        batch_op.alter_column('production_capacity',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300),
               comment=None,
               existing_comment='生产能力',
               existing_nullable=True)
        batch_op.alter_column('quality_certifications',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='质量认证',
               existing_nullable=True)
        batch_op.alter_column('bank_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='开户银行',
               existing_nullable=True)
        batch_op.alter_column('bank_account',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='银行账号',
               existing_nullable=True)
        batch_op.alter_column('bank_branch',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='开户行地址',
               existing_nullable=True)
        batch_op.alter_column('swift_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='SWIFT代码',
               existing_nullable=True)
        batch_op.alter_column('payment_terms',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='付款条件',
               existing_nullable=True)
        batch_op.alter_column('credit_rating',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='信用等级',
               existing_nullable=True)
        batch_op.alter_column('tax_registration_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='税务登记号',
               existing_nullable=True)
        batch_op.alter_column('invoice_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='开票类型',
               existing_nullable=True)
        batch_op.alter_column('rating',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='综合评分',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('rating_updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='评分更新时间',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.alter_column('rating_updated_at',
               existing_type=mysql.DATETIME(),
               comment='评分更新时间',
               existing_nullable=True)
        batch_op.alter_column('rating',
               existing_type=mysql.FLOAT(),
               comment='综合评分',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('invoice_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='开票类型',
               existing_nullable=True)
        batch_op.alter_column('tax_registration_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='税务登记号',
               existing_nullable=True)
        batch_op.alter_column('credit_rating',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='信用等级',
               existing_nullable=True)
        batch_op.alter_column('payment_terms',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='付款条件',
               existing_nullable=True)
        batch_op.alter_column('swift_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='SWIFT代码',
               existing_nullable=True)
        batch_op.alter_column('bank_branch',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='开户行地址',
               existing_nullable=True)
        batch_op.alter_column('bank_account',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='银行账号',
               existing_nullable=True)
        batch_op.alter_column('bank_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='开户银行',
               existing_nullable=True)
        batch_op.alter_column('quality_certifications',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='质量认证',
               existing_nullable=True)
        batch_op.alter_column('production_capacity',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300),
               comment='生产能力',
               existing_nullable=True)
        batch_op.alter_column('factory_area',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='工厂面积（平方米）',
               existing_nullable=True)
        batch_op.alter_column('employee_count',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='员工人数',
               existing_nullable=True)
        batch_op.alter_column('annual_revenue',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='年营业额（万元）',
               existing_nullable=True)
        batch_op.alter_column('main_products',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='主营产品',
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='描述',
               existing_nullable=True)
        batch_op.alter_column('company_description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='公司简介',
               existing_nullable=True)
        batch_op.alter_column('postal_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='邮政编码',
               existing_nullable=True)
        batch_op.alter_column('office_address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300),
               comment='办公地址',
               existing_nullable=True)
        batch_op.alter_column('website',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='公司网站',
               existing_nullable=True)
        batch_op.alter_column('fax',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment='传真',
               existing_nullable=True)
        batch_op.alter_column('company_phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment='公司电话',
               existing_nullable=True)
        batch_op.alter_column('business_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='经营状态',
               existing_nullable=True)
        batch_op.alter_column('company_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='企业类型',
               existing_nullable=True)
        batch_op.alter_column('established_date',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='成立日期',
               existing_nullable=True)
        batch_op.alter_column('registered_address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300),
               comment='注册地址',
               existing_nullable=True)
        batch_op.alter_column('registered_capital',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='注册资本（万元）',
               existing_nullable=True)
        batch_op.alter_column('legal_representative',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='法定代表人',
               existing_nullable=True)
        batch_op.alter_column('tax_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='税号',
               existing_nullable=True)
        batch_op.alter_column('credit_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='信用代码',
               existing_nullable=True)

    with op.batch_alter_table('supplier_quotes', schema=None) as batch_op:
        batch_op.drop_index('ix_supplier_quotes_supplier_rfq_category')
        batch_op.drop_index(batch_op.f('ix_supplier_quotes_status'))
        batch_op.drop_index(batch_op.f('ix_supplier_quotes_quote_number'))
        batch_op.drop_index(batch_op.f('ix_supplier_quotes_category'))
        batch_op.create_index(batch_op.f('idx_sq_quote_number'), ['quote_number'], unique=True)
        batch_op.alter_column('payment_terms',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='供应商报价付款周期(天)',
               existing_server_default=sa.text("'90'"))
        batch_op.drop_column('category')

    with op.batch_alter_table('rfqs', schema=None) as batch_op:
        batch_op.alter_column('payment_terms',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='付款周期(天)',
               existing_server_default=sa.text("'90'"))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_invoices_seller_tax_id'), ['seller_tax_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_invoices_invoice_code'), ['invoice_code'], unique=False)
        batch_op.create_index(batch_op.f('idx_invoices_buyer_tax_id'), ['buyer_tax_id'], unique=False)
        batch_op.alter_column('remark',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='备注说明（中国发票格式）',
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               comment='价税合计',
               existing_nullable=True)
        batch_op.alter_column('amount_before_tax',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               comment='金额合计（不含税）',
               existing_nullable=True)
        batch_op.alter_column('seller_tax_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='销售方纳税人识别号',
               existing_nullable=True)
        batch_op.alter_column('seller_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='销售方名称（供应商）',
               existing_nullable=True)
        batch_op.alter_column('buyer_tax_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='购买方纳税人识别号/统一社会信用代码',
               existing_nullable=True)
        batch_op.alter_column('buyer_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='购买方名称',
               existing_nullable=True)
        batch_op.alter_column('invoice_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='发票代码（10-12位）',
               existing_nullable=True)

    # ### end Alembic commands ###
