"""baseline after full reset

Revision ID: 9fb2b36a253b
Revises: 
Create Date: 2025-10-31 00:20:18.007258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fb2b36a253b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pr_counters',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('date_key', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('seq', mysql.BIGINT(unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pr_counters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pr_counters_date_key'), ['date_key'], unique=True)

    op.create_table('suppliers',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=False),
    sa.Column('business_scope', sa.String(length=500), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('contact_name', sa.String(length=50), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=False),
    sa.Column('contact_email', sa.String(length=120), nullable=False),
    sa.Column('business_license_url', sa.Text(), nullable=True),
    sa.Column('license_file_type', sa.String(length=20), nullable=True),
    sa.Column('license_file_size', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('company_name'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index('idx_suppliers_code', ['code'], unique=False)
        batch_op.create_index('idx_suppliers_status', ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('employee_no', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_no', name='uq_users_employee_no'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pr',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('pr_number', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('urgency', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('owner_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pr', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pr_pr_number'), ['pr_number'], unique=True)

    op.create_table('supplier_categories',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('supplier_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('major_category', sa.String(length=50), nullable=False),
    sa.Column('minor_category', sa.String(length=100), nullable=True),
    sa.Column('full_category', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'major_category', 'minor_category', name='uq_supplier_major_minor')
    )
    with op.batch_alter_table('supplier_categories', schema=None) as batch_op:
        batch_op.create_index('idx_sc_full_category', ['full_category'], unique=False)
        batch_op.create_index('idx_sc_major', ['major_category'], unique=False)
        batch_op.create_index('idx_sc_minor', ['minor_category'], unique=False)
        batch_op.create_index('idx_sc_supplier', ['supplier_id'], unique=False)

    op.create_table('pr_item',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('pr_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('spec', sa.String(length=200), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('classification', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['pr_id'], ['pr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfqs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('pr_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('note', mysql.TEXT(), nullable=True),
    sa.Column('created_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('sent_at', mysql.DATETIME(), nullable=True),
    sa.Column('closed_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pr_id'], ['pr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rfqs', schema=None) as batch_op:
        batch_op.create_index('idx_rfqs_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_rfqs_pr_id', ['pr_id'], unique=False)
        batch_op.create_index('idx_rfqs_status', ['status'], unique=False)

    op.create_table('rfq_items',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('rfq_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('pr_item_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('spec', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('qty', mysql.INTEGER(), nullable=False),
    sa.Column('unit', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('major_category', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('minor_category', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('classification_source', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('classification_score', mysql.LONGTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['pr_item_id'], ['pr_item.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rfq_items', schema=None) as batch_op:
        batch_op.create_index('idx_rfq_items_category', ['category'], unique=False)
        batch_op.create_index('idx_rfq_items_major_category', ['major_category'], unique=False)
        batch_op.create_index('idx_rfq_items_pr_item_id', ['pr_item_id'], unique=False)
        batch_op.create_index('idx_rfq_items_rfq_id', ['rfq_id'], unique=False)

    op.create_table('rfq_notification_tasks',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('rfq_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('supplier_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('retry_count', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('max_retries', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('error_reason', mysql.TEXT(), nullable=True),
    sa.Column('wecom_msg_id', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('sent_at', mysql.DATETIME(), nullable=True),
    sa.Column('next_retry_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rfq_notification_tasks', schema=None) as batch_op:
        batch_op.create_index('idx_rnt_next_retry_at', ['next_retry_at'], unique=False)
        batch_op.create_index('idx_rnt_rfq_id', ['rfq_id'], unique=False)
        batch_op.create_index('idx_rnt_status', ['status'], unique=False)
        batch_op.create_index('idx_rnt_supplier_id', ['supplier_id'], unique=False)

    op.create_table('supplier_quotes',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('rfq_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('supplier_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lead_time', sa.Integer(), nullable=True),
    sa.Column('supplier_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('quote_json', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('responded_at', mysql.DATETIME(), nullable=True),
    sa.Column('expired_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_quotes', schema=None) as batch_op:
        batch_op.create_index('idx_sq_rfq_id', ['rfq_id'], unique=False)
        batch_op.create_index('idx_sq_status', ['status'], unique=False)
        batch_op.create_index('idx_sq_supplier_id', ['supplier_id'], unique=False)
        batch_op.create_index('idx_sq_total_price', ['total_price'], unique=False)

    op.create_table('invoices',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('supplier_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('quote_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('approved_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['supplier_quotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index('idx_invoices_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_invoices_quote_id', ['quote_id'], unique=False)
        batch_op.create_index('idx_invoices_status', ['status'], unique=False)
        batch_op.create_index('idx_invoices_supplier_id', ['supplier_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index('idx_invoices_supplier_id')
        batch_op.drop_index('idx_invoices_status')
        batch_op.drop_index('idx_invoices_quote_id')
        batch_op.drop_index('idx_invoices_created_at')

    op.drop_table('invoices')
    with op.batch_alter_table('supplier_quotes', schema=None) as batch_op:
        batch_op.drop_index('idx_sq_total_price')
        batch_op.drop_index('idx_sq_supplier_id')
        batch_op.drop_index('idx_sq_status')
        batch_op.drop_index('idx_sq_rfq_id')

    op.drop_table('supplier_quotes')
    with op.batch_alter_table('rfq_notification_tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_rnt_supplier_id')
        batch_op.drop_index('idx_rnt_status')
        batch_op.drop_index('idx_rnt_rfq_id')
        batch_op.drop_index('idx_rnt_next_retry_at')

    op.drop_table('rfq_notification_tasks')
    with op.batch_alter_table('rfq_items', schema=None) as batch_op:
        batch_op.drop_index('idx_rfq_items_rfq_id')
        batch_op.drop_index('idx_rfq_items_pr_item_id')
        batch_op.drop_index('idx_rfq_items_major_category')
        batch_op.drop_index('idx_rfq_items_category')

    op.drop_table('rfq_items')
    with op.batch_alter_table('rfqs', schema=None) as batch_op:
        batch_op.drop_index('idx_rfqs_status')
        batch_op.drop_index('idx_rfqs_pr_id')
        batch_op.drop_index('idx_rfqs_created_at')

    op.drop_table('rfqs')
    op.drop_table('pr_item')
    with op.batch_alter_table('supplier_categories', schema=None) as batch_op:
        batch_op.drop_index('idx_sc_supplier')
        batch_op.drop_index('idx_sc_minor')
        batch_op.drop_index('idx_sc_major')
        batch_op.drop_index('idx_sc_full_category')

    op.drop_table('supplier_categories')
    with op.batch_alter_table('pr', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pr_pr_number'))

    op.drop_table('pr')
    op.drop_table('users')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index('idx_suppliers_status')
        batch_op.drop_index('idx_suppliers_code')

    op.drop_table('suppliers')
    with op.batch_alter_table('pr_counters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pr_counters_date_key'))

    op.drop_table('pr_counters')
    # ### end Alembic commands ###
