"""add category column to supplier_categories

Revision ID: d7743944a83e
Revises: 9fb2b36a253b
Create Date: 2025-10-31 13:02:47.686333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7743944a83e'
down_revision = '9fb2b36a253b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=200), nullable=False))
        batch_op.alter_column('major_category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_sc_full_category'))
        batch_op.drop_index(batch_op.f('idx_sc_minor'))
        batch_op.drop_index(batch_op.f('uq_supplier_major_minor'))
        batch_op.create_index('idx_sc_category', ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_categories_major_category'), ['major_category'], unique=False)
        batch_op.create_unique_constraint('uq_supplier_category', ['supplier_id', 'category'])
        batch_op.drop_column('full_category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))
        batch_op.drop_constraint('uq_supplier_category', type_='unique')
        batch_op.drop_index(batch_op.f('ix_supplier_categories_major_category'))
        batch_op.drop_index('idx_sc_category')
        batch_op.create_index(batch_op.f('uq_supplier_major_minor'), ['supplier_id', 'major_category', 'minor_category'], unique=True)
        batch_op.create_index(batch_op.f('idx_sc_minor'), ['minor_category'], unique=False)
        batch_op.create_index(batch_op.f('idx_sc_full_category'), ['full_category'], unique=False)
        batch_op.alter_column('major_category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
        batch_op.drop_column('category')

    # ### end Alembic commands ###
